# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eb1b9631c0ad63fb9b39635a823fe490afdd346f85379e6eb27f268319ada7999a3355f615bcfc63069e4b5fa6a33142975f75a154074f0a35bd2c27f2f31ad

test:
  secret_key_base: 8e62d67ebdb2fb0e1cd70364f1f9a8811344895671df2f8932f7f0b716198457fd9c69fb81d9d88a44801353e6772c5ea5994a5ee90faf19abdd671985d6fbfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
